// const queList = [
//   "🌸 *Sáng ngủ dậy định làm người tử tế, mà đời không cho phép..*",
//   "🌞 *Tôi đã tìm thấy lối thoát trong công việc: thoát vị đĩa đệm.*",
//   "🌧 *Ở cái tuổi đáng ra phải đau khổ vì tình. Thì tôi lại đau lưng.*",
//   "🌿 *Hãy luôn theo đuổi giấc mơ của bạn, bằng cách tắt báo thức và ngủ tiếp.*",
//   "🌕 *Người ta hai bàn tay trắng làm giàu. Còn tôi cũng trắng tay mà làm ra đống nợ.*",
//   "🔥 *Gọi em là dân thường, vì gặp em anh sẽ thương dần.*",
//   "💎 *Ở nhà em ngoan lắm. Mỗi tội em ít ở nhà.*",
//   "🌈 *Mới chơi nói nhẹ cười duyên. Chơi thân mới biết nó điên có nghề!*",
//   "🔥 *Không làm đòi có ăn, chỉ có ăn c**.*",
//   "🌈 *Sống phải chất, chết phải ngất.*",
//   "💎 *Cuộc đời là bể khổ, qua hết bể khổ là đến bể khác!.*",
//   "📌 Nếu hôm nay tệ, đừng lo… mai có thể tệ hơn!",
//   "🌈 Đi làm mà như đi chơi, nhưng cơ bản là vẫn chưa được trả lương đi chơi.",
//   "🌕 Tôi đi đánh cầu chỉ vì muốn chứng minh mình chạy được nhiều hơn lấy trái cầu.",
//   "🌞 Chúng ta không nên buồn và không có gì phải buồn, thì chúng ta cũng không buồn.",
//   "🔥 Kỹ năng đánh cầu 1%, Gáy 99%.",
//   "💎 Tôi không lười, tôi đang trong chế độ tiết kiệm năng lượng.",
//   "🙃 Thôi mày ngủ đi, không thì não bay mất hết!",
//   "😂 Mặt mày hôm nay sáng hơn… mà sáng lên cả drama à?",
//   "🤣 Đừng cười, đằng sau nụ cười là sự thất vọng của cả thế giới.",
//   "😜 Trời ơi, bộ não mày cũ rồi à, phải update bản mới thôi!",
//   "😏 Thôi im đi, đừng làm loãng IQ của cả nhóm nữa.",
//   "😎 Ôi mày vừa mở miệng, vừa làm rớt mood tôi.",
//   "😆 Cẩn thận, nói nhiều quá bị lạc giọng đấy!",
//   "😂 Trí tưởng tượng của mày vừa hết hạn sử dụng rồi.",
//   "🤣 Mày mà thông minh hơn tí, chắc ai cũng phải bỏ chạy.",
//   "🙃 Thôi đi, nói nhiều làm gì, để cười với meme thôi.",
//   "😜 Mặt mày hôm nay cute quá… cute đến mức gây bão mạng.",
//   "😏 Đừng cố tỏ ra hiểu biết, mọi người sẽ thương hại.",
//   "😎 Nếu sự ngu dốt có thể bay, thì mày đã lên vũ trụ rồi.",
//   "😆 Bộ não mày vừa bảo trì, nhờ mày nghỉ tí nhé!",
//   "😂 Thôi, đừng nói nữa, để mồm mày nghỉ ngơi.",
//   "🤣 Chào mừng đến với thế giới của sự lộn xộn… đúng chỗ mày rồi.",
//   "🙃 Mắt mày cười, nhưng tôi thấy não mày đang ngủ.",
//   "😜 Tránh xa, mày vừa thả ra 1 nụ cười nhưng IQ tụt 10 điểm.",
//   "😏 Đừng tưởng ai cũng phải nghe mày, họ đang nghe… meme thôi.",
//   "😎 Mày như Wi-Fi chập chờn, lúc mạnh lúc yếu, lúc làm mọi người phát điên.",
//   "😆 Bộ não mày có chế độ tiết kiệm năng lượng à?",
//   "😂 Mặt mày sáng hơn mặt trời… nhưng là sáng drama!",
//   "🤣 Ngừng ngay, đừng để lời nói của mày làm cả nhóm bối rối.",
//   "🙃 Thôi, cười ít thôi, để mặt mày không biến thành meme.",
//   "😜 Nếu nói nhiều cũng là nghệ thuật, mày là Picasso.",
//   "😏 Tránh xa, mày vừa phát tán năng lượng lộn xộn.",
//   "😎 Nghe mày nói mà cảm giác như đang xem trailer phim hài.",
//   "😆 Thôi, đừng troll nữa, tôi bị hạ huyết áp nhẹ.",
//   "😂 Não mày đang bảo trì, nên tạm thời đừng nói nữa.",
//   "🤣 Chúc mày ngủ ngon, và sáng mai nhớ nạp thêm IQ.",
//   "🙃 Mặt mày đẹp thật, nhưng não mày đang off-line.",
//   "😜 Im đi, đừng làm tụt mood tập thể!",
//   "😏 Nếu mắng yêu thương là nghệ thuật, mày là Van Gogh.",
//   "😎 Nói nhiều quá, tôi sợ não tụi mình bị crash.",
//   "😆 Thôi, đừng troll nữa, meme đã đủ rồi.",
//   "😂 Bộ não mày vừa gửi tín hiệu 'quá tải'.",
//   "🤣 Nghe mày nói mà tôi vừa cười vừa khóc.",
//   "🙃 Thôi đi, tạm thời nghỉ phát ngôn để cứu vãn IQ cả nhóm.",
//   "😜 Nói nhiều quá, tôi sẽ report não mày với quản trị viên.",
//   "😏 Mặt mày cười, nhưng tôi nghi là não mày đang ngủ đông.",
//   "😎 Nếu drama là năng lượng, mày vừa sản xuất đủ điện cho cả thành phố.",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Đừng bốc nữa, cuộc sống của bạn rồi cũng sẽ như cuk thôi!",
//   "🙃 Sống ở đời, đừng trông đợi ai tốt với mình mãi. Họ tốt là may, họ tệ là bình thường!",
//   "🙃 Chỉ có những kẻ yếu lòng mới bị giữ chân bởi những thứ gọi là kỉ niệm!",
// ];

const queList = [
  "🔥 Xin xin cái con c**",
  // "🔥 *Không làm đòi có ăn, chỉ có ăn c**.*",
  // "Ngàn câu động viên không bằng 1 lời khuyên nghỉ việc"
]
module.exports = queList;
